apiVersion: v1
kind: Namespace
metadata:
  name: execution4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution
  namespace: execution4 
spec:
  replicas: 1 # Set replicas to 1(1 pod)
  selector:
    matchLabels:
      app: code-execution
  template:
    metadata:
      labels:
        app: code-execution
    spec:
      containers:
        - name: code-execution-container
          image: vinesen1/cgroupcont:2.0.0
          ports:
            - containerPort: 3000 # Expose app port
          
          resources:
            requests:
              cpu: "512m"
              memory: "256Mi"
            limits:
              cpu: "512m"
              memory: "512Mi"
          securityContext:
            privileged: true 
       
---
apiVersion: v1
kind: Service
metadata:
  namespace: execution4 
  name: code-execution-service
spec:
  selector:
    app: code-execution
  ports:
    - name: http # Name for the application port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
    
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: code-execution-hpa
  namespace: execution4 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: code-execution
  minReplicas: 1 
  maxReplicas: 5 # Maximum number of pods to scale to
  targetCPUUtilizationPercentage: 50 # Target CPU utilization for scaling
